all:
  hosts:
    devops-vm:
      ansible_host: CHANGE_ME
      ansible_user: azureuser
      ansible_ssh_private_key_file: ~/.ssh/devops-lab
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
